services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: musicfreak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - backend

  minio:
    image: minio/minio
    ports:
      - 9000:9000 # S3 API port
      - 9001:9001 # Web UI port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - backend

volumes:
  postgres_data:
  keycloak_data:
  minio_data:

networks:
  backend:
    driver: bridge