services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${DB_MAIN_DB}
      POSTGRES_USER: ${DB_MAIN_USERNAME}
      POSTGRES_PASSWORD: ${DB_MAIN_PASSWORD}
    ports:
      - ${DB_MAIN_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  postgres-keycloak:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${DB_KEYCLOAK_DB}
      POSTGRES_USER: ${DB_KEYCLOAK_USERNAME}
      POSTGRES_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
    ports:
      - ${DB_KEYCLOAK_PORT}:5432
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/${DB_KEYCLOAK_DB}
      KC_DB_USERNAME: ${DB_KEYCLOAK_USERNAME}
      KC_DB_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: false
    ports:
      - ${KEYCLOAK_PORT}:8080
    command:
      - start-dev
    networks:
      - backend
    depends_on:
      - postgres-keycloak

  minio:
    image: minio/minio
    ports:
      - ${S3_PORT}:9000
      - ${S3_WEB_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${S3_USERNAME}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    volumes:
      - minio_data:/data
    command: server --console-address ":${S3_WEB_PORT}" /data
    networks:
      - backend

  app:
    image: musicfreak:5.2.0
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      QUARKUS_PROFILE: stage
      APP_PORT: ${APP_PORT}
      DB_MAIN_PORT: ${DB_MAIN_PORT}
      DB_MAIN_DB: ${DB_MAIN_DB}
      DB_MAIN_USERNAME: ${DB_MAIN_USERNAME}
      DB_MAIN_PASSWORD: ${DB_MAIN_PASSWORD}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      S3_PORT: ${S3_PORT}
      S3_USERNAME: ${S3_USERNAME}
      S3_PASSWORD: ${S3_PASSWORD}
    depends_on:
      - postgres
      - keycloak
      - minio
    networks:
      - backend

volumes:
  postgres_data:
  postgres_keycloak_data:
  minio_data:

networks:
  backend:
    driver: bridge
