quarkus:
  devservices:
    enabled: true
  oidc:
    enabled: false
  datasource:
    db-kind: postgresql
    username: test
    password: test
  flyway:
    enabled: true
    migrate-at-start: true
  s3:
    path-style-access: true
    aws:
      region: us-east-1
      credentials:
        type: static