quarkus:
  devservices:
    enabled: false
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/musicfreak
    username: admin
    password: admin
  flyway:
    enabled: true
    migrate-at-start: true
    locations: classpath:db/migration
  oidc:
    auth-server-url: http://localhost:8080/realms/musicfreak
    application-type: service
    token:
      issuer: http://localhost:8080/realms/musicfreak
    authentication:
      jwt:
        required: true

values:
  path:
    albums: /home/alex/development/uploads/musicfreak/albums