quarkus:
  devservices:
    enabled: false
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://postgres:${DB_MAIN_PORT}/${DB_MAIN_DB}
    username: ${DB_MAIN_USERNAME}
    password: ${DB_MAIN_PASSWORD}
  flyway:
    enabled: true
    migrate-at-start: true
  oidc:
    auth-server-url: http://keycloak:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}
    application-type: service
    token:
      issuer: http://localhost:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}
    authentication:
      jwt:
        required: true
  s3:
    endpoint-override: http://minio:${S3_PORT}
    path-style-access: true
    aws:
      credentials:
        type: static
        static-provider:
          access-key-id: ${S3_USERNAME}
          secret-access-key: ${S3_PASSWORD}