quarkus:
  devservices:
    enabled: true
  oidc:
    enabled: false
  datasource:
    db-kind: postgresql
    username: test
    password: test
  flyway:
    enabled: true
    migrate-at-start: true

minio:
  endpoint: http://localhost:${MINIO_S3_PORT}
  access-key: test
  secret-key: test