quarkus:
  devservices:
    enabled: false
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:${DB_MAIN_PORT}/${DB_MAIN_DB}
    username: ${DB_MAIN_USERNAME}
    password: ${DB_MAIN_PASSWORD}
  flyway:
    enabled: true
    migrate-at-start: true
  oidc:
    auth-server-url: http://localhost:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}
    application-type: service
    token:
      principal-claim: sub
  s3:
    endpoint-override: http://localhost:${S3_PORT}
    path-style-access: true
    aws:
      region: us-east-1
      credentials:
        type: static
        static-provider:
          access-key-id: ${S3_USERNAME}
          secret-access-key: ${S3_PASSWORD}