quarkus:
  devservices:
    enabled: false
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://postgres:${DB_MAIN_PORT}/${DB_MAIN_DB}
    username: ${DB_MAIN_USERNAME}
    password: ${DB_MAIN_PASSWORD}
  flyway:
    enabled: true
    migrate-at-start: true
  oidc:
    auth-server-url: http://keycloak:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}
    application-type: service
    token:
      issuer: http://localhost:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}
    authentication:
      jwt:
        required: true

minio:
  endpoint: http://minio:${MINIO_S3_PORT}
  access-key: ${MINIO_USERNAME}
  secret-key: ${MINIO_PASSWORD}