services:
  postgres:
    container_name: musicfreak_postgres
    image: postgres:17.4
    environment:
      POSTGRES_DB: musicfreak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - musicfreak_default
  keycloak:
    container_name: musicfreak_keycloak
    image: quay.io/keycloak/keycloak:26.3.2
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command:
      - start-dev
    networks:
      - musicfreak_default

networks:
  musicfreak_default:
    driver: bridge
    external: true