services:
  postgres:
    container_name: musicfreak_postgres
    image: postgres:17.4
    environment:
      POSTGRES_DB: musicfreak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 127.0.0.1:5432:5432